meilisearch:
  # API address of meilisearch
  api_url: http://127.0.0.1:7700
  # master key https://www.meilisearch.com/docs/learn/security/differences_master_api_keys#master-key
  api_key: foobar

source:
   # database engine mongo, mysql, postgres
  engine: mongo
  uri: "mongodb://localhost:27017"
  database: "foobar"

bridges:
    # collection in mongo or table in sql
  - collection: "user"
    # index name for meilisearch
    index_name: "user"
    # primary_keys set pk for fields in meilisearch
    primary_keys:
      - id
      - age

    # fields is list column or field in database you can set custom name for fields by passing value to index
    # in meilisearch key is original name of in source database, value is optional.
    fields:
      _id: id
      first_name:
      last_name:
      age:
      created_at:

    # set custom settings for index in meilisearch
    settings:
      # list of strings Meilisearch should parse as a single term, default is empty
      # https://www.meilisearch.com/docs/reference/api/settings#dictionary
      dictionary:
        - foo
        - bar

      # fields displayed in the returned documents, default is all attributes
      # https://www.meilisearch.com/docs/reference/api/settings#displayed-attributes
      displayed_attributes:
        - foo
        - bar

      # faceting settings
      # https://www.meilisearch.com/docs/reference/api/settings#faceting-object
      faceting:
        # maximum number of facet values returned for each facet. Values are sorted in ascending lexicographical order
        # default is 100
        max_values_perFacet: 100

        # customize facet order to sort by descending value count (count) or ascending alphanumeric order (alpha)
        # default is "*": "alpha"
        sort_facet_values_by:
          - "*": "alpha"
          - "x": "count"

      # attributes to use as filters and facets, default is empty
      # https://www.meilisearch.com/docs/reference/api/settings#filterable-attributes
      filterable_attributes:
        - first_name
        - last_name

      # fields in which to search for matching query words sorted by order of importance, default is all attributes ["*"]
      # https://www.meilisearch.com/docs/reference/api/settings#searchable-attributes
      searchable_attributes:
        - first_name
        - last_name
        - age

      # attributes to use when sorting search results, default is empty
      # https://www.meilisearch.com/docs/reference/api/settings#sortable-attributes
      sortable_attributes:
        - age

      # pagination settings
      # https://www.meilisearch.com/docs/reference/api/settings#pagination
      pagination:
        # the maximum number of search results Meilisearch can return, default is 1000
        # note: setting maxTotalHits to a value higher than the default will negatively impact search performance.
        # setting maxTotalHits to values over 20000 may result in queries taking seconds to complete.
        max_total_hits: 500

      # precision level when calculating the proximity ranking rule, default is "byWord"
      # https://www.meilisearch.com/docs/reference/api/settings#proximity-precision
      proximity_precision: "byWord"

      # list of ranking rules in order of importance,
      # default is ["words", "typo", "proximity", "attribute", "sort", "exactness"]
      # https://www.meilisearch.com/docs/reference/api/settings#ranking-rules
      ranking_rules:
        - "words"
        - "typo"

      # maximum duration of a search query for null set 0, default is 1500
      # https://www.meilisearch.com/docs/reference/api/settings#search-cutoff
      search_cutoff_ms: 500

      # list of characters delimiting where one term begins and ends, default is empty
      # https://www.meilisearch.com/docs/reference/api/settings#separator-tokens
      separator_tokens:
        - foo
        - bar

      # list of characters not delimiting where one term begins and ends, default is empty
      # https://www.meilisearch.com/docs/reference/api/settings#non-separator-tokens
      non_separator_tokens:
        - foo
        - bar

      # list of words ignored by Meilisearch when present in search queries, default is empty
      # https://www.meilisearch.com/docs/reference/api/settings#stop-words
      stop_words:
        - foo
        - bar

      # list of associated words treated similarly, default is empty
      # https://www.meilisearch.com/docs/reference/api/settings#synonyms
      synonyms:
        wolverine:
          - foo
          - bar
        logan:
          - x
          - y
          - z

      # typo tolerance settings
      # https://www.meilisearch.com/docs/reference/api/settings#typo-tolerance
      typo_tolerance:
        # whether typo tolerance is enabled or not, default is true
        enabled: true

        # the minimum word size for accepting 2 typos; must be between oneTypo and 255, default is 9
        min_word_size_for_typos:
          "one_typo": 5,
          "two_typos": 9

        # an array of words for which the typo tolerance feature is disabled, default is empty
        disable_on_words:
          - foo
          - bar

        # an array of attributes for which the typo tolerance feature is disabled, default is empty
        disable_on_attributes:
          - foo
          - bar

  - collection: "foo"
    index_name: "bar"
    primary_keys:
      - id
      - age

    fields:
      _id: id
      first_name:
      last_name:
      age:
      created_at:

    settings:
